export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const SET_ORDER_REQUEST = 'SET_ORDER_REQUEST';
export const SET_ORDER_FAILURE = 'SET_ORDER_FAILURE';
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
